#!/bin/bash
# usage: ./runCDN -p <port> -o <origin> -n <name> -u <username> -i <keyfile>
# usage: ./runCDN -p 40006 -o ec2-54-158-114-217.compute-1.amazonaws.com -n cs5700cdn.example.com -u team-6 -i team-6.pem 

ssh -i ${10} $8@ec2-54-213-74-38.us-west-2.compute.amazonaws.com "./httpserver -p $2 -o $4"
ssh -i ${10} $8@ec2-3-92-59-2.compute-1.amazonaws.com "./httpserver -p $2 -o $4"
ssh -i ${10} $8@ec2-13-209-67-180.ap-northeast-2.compute.amazonaws.com "./httpserver -p $2 -o $4"
ssh -i ${10} $8@ec2-35-182-244-184.ca-central-1.compute.amazonaws.com "./httpserver -p $2 -o $4"
ssh -i ${10} $8@ec2-54-93-225-118.eu-central-1.compute.amazonaws.com "./httpserver -p $2 -o $4"
